services:
  app:
    container_name: arcanimal_app
    build: .
    command: yarn run start:dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - db
    restart: always

  db:
    container_name: arcanimal_db
    image: postgres:16
    ports:
      - "9668:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
